###variables
@host=localhost:5000
@apikey=key1
@apikey2=key2
###variables

GET http://{{host}}/drinks HTTP/1.1
Api-Key: {{apikey}}
###
GET http://{{host}}/drinks HTTP/2
Api-Key: "fakekey"
###
GET http://{{host}}/drinks HTTP/2
###

GET http://localhost:5000/drinks/1 HTTP/2
Api-Key: {{apikey2}}
###
GET http://localhost:5000/drinks/1 HTTP/1.1
Api-Key: {{apikey2}}
api-version: 2.0      
###
POST http://localhost:5000/drinks/Add HTTP/1.1
Api-Key: {{apikey2}}
Content-Type: application/json

{
    "DbDrinkId": "aRandomNumber2",
    "Name": "aRandomNumber2",
    "AlternateName": "Tommy's Margarita",
    "Category": "Shake",
    "Iba": "Contemporary Classics",
    "Alcoholic": true,
    "ImageUrl": "https://www.thecocktaildb.com/images/media/drink/wpxpvu1439905379.jpg",
    "IsEdited": false,
    "IsDeleted": false,
    "GlassType": {
        "Name": "CoolGLass"
    },
    "Ingredient": {
      "Ingredient1":"Yum",   
      "Ingredient3":"Yum2",   
      "Ingredient2":"Yum3",
      "IsDeleted": false
    },
    "Measurement": {
        "Measure1":"1 cup",
        "Measure2":"2 cups",
        "Measure3":"3 cups",
      "IsDeleted": false
    }
}
###
PUT http://localhost:5000/drinks
Api-Key: {{apikey2}}
Content-Type: application/json

{
    "DbDrinkId": "aRandomNumber8",
    "Name": "aRandomNumber8",
    "AlternateName": "Tommy's Favorite",
    "Category": "Shake",
    "Iba": "Contemporary Classics",
    "Alcoholic": true,
    "ImageUrl": "https://www.thecocktaildb.com/images/media/drink/wpxpvu1439905379.jpg",
    "IsEdited": false,
    "IsDeleted": false,
    "GlassType": {
        "Name": "CoolGLass"
    },
    "Ingredient": {
      "Ingredient1":"Yum",   
      "Ingredient3":"Yum2",   
      "Ingredient2":"Yum3",
      "IsDeleted": false
    },
    "Measurement": {
        "Measure1":"1 cup",
        "Measure2":"2 cups",
        "Measure3":"4 cups",
      "IsDeleted": false
    }
}
###
DELETE http://localhost:5000/drinks/12
Api-Key: {{apikey2}}
###
GET http://localhost:5000/drinks/categories
Api-Key: {{apikey2}}
###
GET http://localhost:5000/drinks/category/Shake
Api-Key: {{apikey2}}
###
GET http://localhost:5000/glasses
Api-Key: {{apikey2}}
### 
GET http://localhost:5000/drinks/glasses/Cocktail glass
Api-Key: {{apikey2}}
###
GET http://localhost:5000/drinks/alcoholic/alcoholic
Api-Key: {{apikey2}}
###
GET http://localhost:5000/drinks/alcoholic/non-alcoholic
Api-Key: {{apikey2}}
###
GET http://localhost:5000/glasses/4
Api-Key: {{apikey2}}
###
POST  http://localhost:5000/glasses/Add
Content-Type: application/json
Api-Key: {{apikey2}}

{
    "name": "Potential glasss"
}
###
DELETE http://localhost:5000/glasses/4
Api-Key: {{apikey2}}
###
GET http://localhost:5000/ingredients
Api-Key: {{apikey2}}
###
GET http://localhost:5000/ingredients/2
Api-Key: {{apikey2}}
###
GET http://localhost:5000/download/Cocktail
Api-Key: {{apikey2}}
### 
POST http://localhost:5000/upload
Api-Key: {{apikey2}}
###
GET http://localhost:5000/setup
Api-Key: {{apikey2}}
###
GET http://localhost:5000/stop
Api-Key: {{apikey2}}
###
GET http://localhost:5000/start
Api-Key: {{apikey2}}
###

